name: Android CI

on:
  # 触发工作流程的事件，例如推送代码到主分支
  # push:
    # branches:
    #   - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Java环境
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # 设置Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      # 构建项目
      - name: Build with Gradle
        run: ./gradlew build
